"""Additional dispersed-initialization sensitivity audit for APPLIES q=2.

This script is a companion to ``audit_null_model_chains_v3.py``. It does not
replace the frozen same-start audit. Each formal chain starts from an
independently randomized fixed-margin realization generated by a separate RNG
stream, then uses the same formal burn-in and retained-sample design.

Outputs include both the mean-centered two-sided MCMC tail diagnostic p_MC and
the directional upper-tail sensitivity diagnostic p_plus.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import math
import platform
import random
import sys
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

import audit_null_model_chains_v3 as base  # noqa: E402
import bipartite_null_test as null  # noqa: E402
import representation_diagnostic as rd  # noqa: E402


DEFAULT_CHAIN_SEEDS = [2026090201, 2026090202, 2026090203, 2026090204]
DEFAULT_INITIALIZATION_SEEDS = [2026091201, 2026091202, 2026091203, 2026091204]
PROGRAM_VERSION = "1.0.0-20260902"


def edge_symmetric_difference(a, b):
    return len(a.symmetric_difference(b))


def validate_margins(edges, entity_degrees, context_sizes, edge_count):
    current_entity_degrees, current_context_sizes = base.degree_maps(edges)
    return (
        current_entity_degrees == entity_degrees
        and current_context_sizes == context_sizes
        and len(edges) == edge_count
    )


def effective_sample_size(values):
    """Geyer initial positive sequence ESS estimator."""
    x = [float(v) for v in values]
    n = len(x)
    if n < 2:
        return {"ess": float(n), "tau": 1.0, "max_lag_used": 0,
                "method": "Geyer initial positive sequence"}

    mean = sum(x) / n
    centered = [v - mean for v in x]
    gamma0 = sum(v * v for v in centered) / n
    if gamma0 == 0:
        return {"ess": float(n), "tau": 1.0, "max_lag_used": 0,
                "method": "Geyer initial positive sequence"}

    def rho(lag):
        gamma = sum(
            centered[i] * centered[i + lag]
            for i in range(n - lag)
        ) / n
        return gamma / gamma0

    rho_sum = 0.0
    max_lag_used = 0
    lag = 1
    while lag < n:
        pair_sum = rho(lag)
        if lag + 1 < n:
            pair_sum += rho(lag + 1)
        if pair_sum <= 0:
            break
        rho_sum += pair_sum
        max_lag_used = min(lag + 1, n - 1)
        lag += 2

    tau = max(1.0, 1.0 + 2.0 * rho_sum)
    ess = min(float(n), max(1.0, n / tau))
    return {
        "ess": ess,
        "tau": tau,
        "max_lag_used": max_lag_used,
        "method": "Geyer initial positive sequence",
    }



def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def software_metadata(input_path: Path) -> dict[str, object]:
    """Record provenance for the actual dispersed-start audit and imports."""
    source_paths = [
        Path(__file__).resolve(),
        Path(base.__file__).resolve(),
        Path(null.__file__).resolve(),
        Path(rd.__file__).resolve(),
    ]

    # Preserve order while avoiding duplicate paths.
    unique_sources = list(dict.fromkeys(source_paths))

    return {
        "program": Path(__file__).name,
        "program_version": PROGRAM_VERSION,
        "python": sys.version,
        "python_implementation": platform.python_implementation(),
        "platform": platform.platform(),
        "rng": "Python random.Random using MT19937",
        "command": [str(item) for item in sys.argv],
        "run_timestamp_local": datetime.now().astimezone().isoformat(),
        "source_sha256": {
            path.name: sha256(path)
            for path in unique_sources
        },
        "source_paths": {
            path.name: str(path)
            for path in unique_sources
        },
        "input_file": str(input_path.resolve()),
        "input_sha256": sha256(input_path),
    }

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data-dir", type=Path, default=rd.DEFAULT_DATA)
    parser.add_argument("--relation", choices=["APPLIES"], default="APPLIES")
    parser.add_argument("--q", type=int, default=2)
    parser.add_argument("--chain-seeds", type=int, nargs="+", default=DEFAULT_CHAIN_SEEDS)
    parser.add_argument(
        "--initialization-seeds",
        type=int,
        nargs="+",
        default=DEFAULT_INITIALIZATION_SEEDS,
    )
    parser.add_argument("--samples-per-chain", type=int, default=1000)
    parser.add_argument("--initialization-edge-multiplier", type=int, default=1000)
    parser.add_argument("--burn-in-edge-multiplier", type=int, default=100)
    parser.add_argument("--sampling-interval-edge-multiplier", type=int, default=1)
    parser.add_argument("--burn-in-checkpoints", type=int, default=20)
    parser.add_argument(
        "--manual-trace-review",
        choices=["pending", "pass", "fail"],
        default="pending",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=ROOT / "results" / "applies_q2_dispersed_start_audit_v1_20260902.json",
    )
    args = parser.parse_args()

    if len(args.chain_seeds) < 2 or len(set(args.chain_seeds)) != len(args.chain_seeds):
        parser.error("provide at least two distinct chain seeds")
    if len(args.initialization_seeds) != len(args.chain_seeds):
        parser.error("initialization seeds must match chain-seed count")
    if len(set(args.initialization_seeds)) != len(args.initialization_seeds):
        parser.error("initialization seeds must be distinct")
    if min(
        args.q,
        args.samples_per_chain,
        args.initialization_edge_multiplier,
        args.burn_in_edge_multiplier,
        args.sampling_interval_edge_multiplier,
        args.burn_in_checkpoints,
    ) < 1:
        parser.error("q, samples, multipliers, and checkpoints must be positive")

    input_path = args.data_dir / rd.EDGE_FILES[args.relation]
    original_edges = set(rd.load_edges(args.data_dir, args.relation))
    entities = sorted({entity for entity, _ in original_edges})
    entity_degrees, context_sizes = base.degree_maps(original_edges)
    edge_count = len(original_edges)

    initialization_attempts = args.initialization_edge_multiplier * edge_count
    burn_in_attempts = args.burn_in_edge_multiplier * edge_count
    sampling_interval = args.sampling_interval_edge_multiplier * edge_count

    observed_k, observed_p, observed_s, observed_m = base.representation_vectors(
        entities, original_edges, args.q
    )
    observed_rho = float(rd.spearman(observed_k, observed_p))

    base_batch, remainder = divmod(burn_in_attempts, args.burn_in_checkpoints)

    chain_reports = []
    rho_chains = []
    starting_graphs = []
    all_preserved = True

    for chain_id, (chain_seed, init_seed) in enumerate(
        zip(args.chain_seeds, args.initialization_seeds), start=1
    ):
        # Stage 0: generate a distinct fixed-margin starting realization.
        init_rng = random.Random(init_seed)
        edges = set(original_edges)
        init_accepted = null.edge_switches(edges, initialization_attempts, init_rng)

        init_preserved = validate_margins(
            edges, entity_degrees, context_sizes, edge_count
        )
        if not init_preserved:
            raise RuntimeError(f"initialization margin failure in chain {chain_id}")

        start_edges = set(edges)
        starting_graphs.append(start_edges)
        start_k, start_p, start_s, start_m = base.representation_vectors(
            entities, start_edges, args.q
        )

        # Formal chain: independent RNG stream.
        rng = random.Random(chain_seed)
        burn_in_accepted = 0
        burn_in_trace = []
        attempts_so_far = 0

        for checkpoint in range(args.burn_in_checkpoints):
            batch = base_batch + (1 if checkpoint < remainder else 0)
            accepted = null.edge_switches(edges, batch, rng)
            burn_in_accepted += accepted
            attempts_so_far += batch
            k, p, s, m = base.representation_vectors(entities, edges, args.q)
            burn_in_trace.append(
                {
                    "checkpoint": checkpoint + 1,
                    "proposal_attempts": attempts_so_far,
                    "accepted_switches_cumulative": burn_in_accepted,
                    "rho_r": float(rd.spearman(k, p)),
                    "sum_K_r": sum(k),
                    "sum_P_q_r": sum(p),
                    "sum_S_q_r": sum(s),
                    "sum_M_q_r_auxiliary": sum(m),
                }
            )

        retained = []
        sampling_accepted = 0
        preservation_failures = 0

        for sample_id in range(1, args.samples_per_chain + 1):
            accepted = null.edge_switches(edges, sampling_interval, rng)
            sampling_accepted += accepted
            preserved = validate_margins(
                edges, entity_degrees, context_sizes, edge_count
            )
            preservation_failures += int(not preserved)
            k, p, s, m = base.representation_vectors(entities, edges, args.q)
            retained.append(
                {
                    "sample_id": sample_id,
                    "proposal_attempts_after_burn_in": sample_id * sampling_interval,
                    "accepted_switches_since_previous_sample": accepted,
                    "margins_preserved_exactly": preserved,
                    "rho_r": float(rd.spearman(k, p)),
                    "sum_K_r": sum(k),
                    "sum_P_q_r": sum(p),
                    "sum_S_q_r": sum(s),
                    "sum_M_q_r_auxiliary": sum(m),
                }
            )

        all_preserved = all_preserved and preservation_failures == 0
        rho_values = [float(record["rho_r"]) for record in retained]
        rho_chains.append(rho_values)

        sampling_total = args.samples_per_chain * sampling_interval
        formal_total = burn_in_attempts + sampling_total
        formal_accepted = burn_in_accepted + sampling_accepted

        chain_reports.append(
            {
                "chain_id": chain_id,
                "chain_seed": chain_seed,
                "initialization": {
                    "seed": init_seed,
                    "proposal_attempts": initialization_attempts,
                    "accepted_switches": init_accepted,
                    "acceptance_rate": init_accepted / initialization_attempts,
                    "margins_preserved_exactly": init_preserved,
                    "edge_symmetric_difference_from_observed": edge_symmetric_difference(
                        start_edges, original_edges
                    ),
                    "starting_rho": float(rd.spearman(start_k, start_p)),
                    "starting_vector_totals": {
                        "sum_K": sum(start_k),
                        "sum_P_q": sum(start_p),
                        "sum_S_q": sum(start_s),
                        "sum_M_q_auxiliary": sum(start_m),
                    },
                },
                "formal_chain": {
                    "burn_in_proposal_attempts": burn_in_attempts,
                    "sampling_interval_proposal_attempts": sampling_interval,
                    "retained_samples": args.samples_per_chain,
                    "sampling_proposal_attempts": sampling_total,
                    "total_proposal_attempts": formal_total,
                    "burn_in_accepted_switches": burn_in_accepted,
                    "sampling_accepted_switches": sampling_accepted,
                    "accepted_switches_total": formal_accepted,
                    "acceptance_rate_total": formal_accepted / formal_total,
                },
                "burn_in_trace": burn_in_trace,
                "burn_in_trace_summary": base.trace_summary(
                    [float(item["rho_r"]) for item in burn_in_trace]
                ),
                "preservation_failures_across_retained_samples": preservation_failures,
                "retained_rho_summary": base.descriptive_summary(rho_values),
                "ess_rho_r": effective_sample_size(rho_values),
                "retained_rho_records": retained,
            }
        )

    pooled_rho = [value for chain in rho_chains for value in chain]
    pooled_summary = base.descriptive_summary(pooled_rho)
    pooled_center = pooled_summary["mean"]
    observed_distance = abs(observed_rho - pooled_center)

    pooled_two_sided_count = 0
    pooled_upper_count = 0

    for report in chain_reports:
        two_sided = []
        upper = []
        for record in report["retained_rho_records"]:
            rho_r = float(record["rho_r"])
            i_two = int(abs(rho_r - pooled_center) >= observed_distance)
            i_upper = int(rho_r >= observed_rho)
            record["two_sided_tail_indicator"] = i_two
            record["upper_tail_indicator"] = i_upper
            two_sided.append(i_two)
            upper.append(i_upper)

        n = len(two_sided)
        c_two = sum(two_sided)
        c_upper = sum(upper)
        f_two = c_two / n
        f_upper = c_upper / n
        ess_two = effective_sample_size(two_sided)
        ess_upper = effective_sample_size(upper)

        report["two_sided_tail_summary"] = {
            "definition": (
                "abs(rho_r - pooled_retained_mean) >= "
                "abs(rho_observed - pooled_retained_mean)"
            ),
            "count": c_two,
            "frequency": f_two,
            "ess": ess_two,
            "mcse": math.sqrt(f_two * (1 - f_two) / float(ess_two["ess"])),
        }
        report["upper_tail_summary"] = {
            "definition": "rho_r >= rho_observed",
            "count": c_upper,
            "frequency": f_upper,
            "ess": ess_upper,
            "mcse": math.sqrt(f_upper * (1 - f_upper) / float(ess_upper["ess"])),
        }
        pooled_two_sided_count += c_two
        pooled_upper_count += c_upper

    pairwise_start_distances = []
    for i, j in itertools.combinations(range(len(starting_graphs)), 2):
        pairwise_start_distances.append(
            {
                "chain_i": i + 1,
                "chain_j": j + 1,
                "edge_symmetric_difference": edge_symmetric_difference(
                    starting_graphs[i], starting_graphs[j]
                ),
            }
        )

    r_hat = base.split_r_hat(rho_chains)
    min_ess_rho = min(float(r["ess_rho_r"]["ess"]) for r in chain_reports)
    min_ess_two = min(
        float(r["two_sided_tail_summary"]["ess"]["ess"]) for r in chain_reports
    )
    min_ess_upper = min(
        float(r["upper_tail_summary"]["ess"]["ess"]) for r in chain_reports
    )

    r_hat_pass = r_hat is not None and r_hat < 1.01
    ess_pass = min_ess_rho >= 400

    report = {
        "run_identity": {
            "status": (
                "additional dispersed-initialization sensitivity audit; "
                "does not replace the frozen same-start audit"
            ),
            "program_version": PROGRAM_VERSION,
        },
        "design": {
            "relation": args.relation,
            "q": args.q,
            "edge_count_E": edge_count,
            "chains": len(args.chain_seeds),
            "chain_seeds": args.chain_seeds,
            "initialization_seeds": args.initialization_seeds,
            "initialization_randomization": {
                "proposal_attempts": initialization_attempts,
                "formula": f"{args.initialization_edge_multiplier}|E|",
                "unit": "proposal attempts",
            },
            "formal_burn_in": {
                "proposal_attempts": burn_in_attempts,
                "formula": f"{args.burn_in_edge_multiplier}|E|",
            },
            "sampling_interval": {
                "proposal_attempts": sampling_interval,
                "formula": f"{args.sampling_interval_edge_multiplier}|E|",
            },
            "retained_samples_per_chain": args.samples_per_chain,
            "total_retained_samples": len(pooled_rho),
            "invalid_proposals": (
                "counted as proposal attempts and treated as Markov-chain self-loops"
            ),
        },
        "statistic_definition": {
            "rho_r": "midrank Spearman correlation between K_r and P_q_r",
            "observed_rho": observed_rho,
            "observed_vector_totals": {
                "sum_K": sum(observed_k),
                "sum_P_q": sum(observed_p),
                "sum_S_q": sum(observed_s),
                "sum_M_q_auxiliary": sum(observed_m),
            },
        },
        "initialization_separation": {
            "distance_metric": "edge-set symmetric difference cardinality",
            "distance_from_observed": [
                {
                    "chain_id": r["chain_id"],
                    "distance": r["initialization"][
                        "edge_symmetric_difference_from_observed"
                    ],
                }
                for r in chain_reports
            ],
            "pairwise_start_distances": pairwise_start_distances,
        },
        "chain_reports": chain_reports,
        "pooled_reference": {
            "retained_rho_summary": pooled_summary,
            "mean_centered_two_sided": {
                "tail_count": pooled_two_sided_count,
                "tail_frequency": pooled_two_sided_count / len(pooled_rho),
                "plus_one_p_MC": (pooled_two_sided_count + 1)
                / (len(pooled_rho) + 1),
                "interpretation": (
                    "approximate mean-centered two-sided MCMC tail diagnostic"
                ),
            },
            "directional_upper_tail": {
                "tail_count": pooled_upper_count,
                "tail_frequency": pooled_upper_count / len(pooled_rho),
                "plus_one_p_plus": (pooled_upper_count + 1)
                / (len(pooled_rho) + 1),
                "interpretation": (
                    "approximate directional upper-tail MCMC sensitivity diagnostic"
                ),
            },
        },
        "diagnostics": {
            "split_R_hat_rho_r": r_hat,
            "minimum_per_chain_ESS_rho_r": min_ess_rho,
            "minimum_per_chain_ESS_two_sided_tail_indicator": min_ess_two,
            "minimum_per_chain_ESS_upper_tail_indicator": min_ess_upper,
            "criteria": {"split_R_hat": "<1.01", "minimum_ESS_rho_r": ">=400"},
            "manual_trace_review": {
                "status": args.manual_trace_review,
                "criterion": (
                    "no evident sustained or common-direction trend across "
                    "the four formal burn-in traces"
                ),
            },
        },
        "preservation_checks": {
            "initialization_margins_checked": True,
            "all_initializations_preserved_exactly": all(
                bool(r["initialization"]["margins_preserved_exactly"])
                for r in chain_reports
            ),
            "every_retained_state_checked": True,
            "all_retained_samples_preserved_exactly": all_preserved,
        },
        "software": software_metadata(input_path),
        "audit_status": (
            "PASS"
            if all_preserved
            and r_hat_pass
            and ess_pass
            and args.manual_trace_review == "pass"
            else "PASS_PENDING_MANUAL_TRACE_REVIEW"
            if all_preserved
            and r_hat_pass
            and ess_pass
            and args.manual_trace_review == "pending"
            else "REVIEW"
        ),
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(report, ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )

    print(
        json.dumps(
            {
                "output": str(args.output),
                "observed_rho": observed_rho,
                "pooled_retained_mean": pooled_summary["mean"],
                "pooled_q025": pooled_summary["q025"],
                "pooled_q500": pooled_summary["q500"],
                "pooled_q975": pooled_summary["q975"],
                "plus_one_p_MC": (pooled_two_sided_count + 1)
                / (len(pooled_rho) + 1),
                "plus_one_p_plus": (pooled_upper_count + 1)
                / (len(pooled_rho) + 1),
                "split_R_hat_rho_r": r_hat,
                "minimum_per_chain_ESS_rho_r": min_ess_rho,
                "minimum_per_chain_ESS_two_sided_tail_indicator": min_ess_two,
                "minimum_per_chain_ESS_upper_tail_indicator": min_ess_upper,
                "audit_status": report["audit_status"],
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
